version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm install --prefix ui
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run verify
      - run: npm run build
      - run: echo "module.exports = { API_KEY\: `echo $API_KEY` };" > config/production.js
      - run: cat config/production.js
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
            - lib
            - config
            - index.js
            - package.json
            - package-lock.json
            - app.yaml
            - .gcloudignore
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: ls -latr /tmp/workspace
      - run: gcloud app deploy